spring:
  mvc:
    cors:
      Origin: http://localhost:4200
      allow-credentials: true
      allowed-origins: http://localhost:4200
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: Origin, X-Requested-With, Content-Type, Accept
      Access-Control-Allow-Origin: http://localhost:4200
      Access-Control-Allow-Methods: DELETE, GET , POST , PUT , HEAD , OPTIONS
      Access-Control-Request-Method: DELETE, GET , POST , PUT , HEAD , OPTIONS
